# Reinforcement Learning Project Configuration

# Environment settings
environment:
  name: "CartPole-v1"
  max_episode_steps: 500
  render_mode: null  # Set to "human" for visualization

# Training settings
training:
  episodes: 1000
  max_steps_per_episode: 500
  gamma: 0.99
  learning_rate: 1e-3
  batch_size: 64
  update_frequency: 1
  
# Model architecture
model:
  hidden_size: 128
  activation: "relu"
  dropout: 0.0
  
# Algorithms to implement
algorithms:
  actor_critic:
    enabled: true
    baseline: true
  ppo:
    enabled: true
    clip_ratio: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
  sac:
    enabled: true
    tau: 0.005
    alpha: 0.2
  td3:
    enabled: true
    tau: 0.005
    policy_noise: 0.2
    noise_clip: 0.5
    
# Logging and monitoring
logging:
  level: "INFO"
  tensorboard: true
  wandb: false
  log_frequency: 10
  
# Checkpointing
checkpointing:
  save_frequency: 100
  max_checkpoints: 5
  
# Evaluation
evaluation:
  eval_frequency: 50
  eval_episodes: 10
  
# Visualization
visualization:
  plot_frequency: 50
  save_plots: true
  plot_dir: "plots"
